name: AUR Release

on:
  push:
    tags:
      - 'v*'

jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update AUR
        uses: KSXGitHub/github-actions-deploy-aur@master
        with:
          pkgname: mouse-debounce
          pkgbuild: ./PKGBUILD
          commit_username: mishl
          commit_email: meow@mishl.dev
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ github.ref_name }}"
          allow_out_of_date_packages: true